#!/usr/bin/env bash
set -Eeuo pipefail

# One-time, idempotent AEGIS setup. Run this before BASELINE.
# Usage: prepare_sandbox.sh <repository> [npm|pnpm|yarn]

repo_dir="${1:?repository path required}"
manager="${2:-}"
skill_dir="$(cd "$(dirname "$0")/.." && pwd)"
marker="$skill_dir/.aegis-prepared"
runtime_env="$skill_dir/.aegis-node-env"

if ! command -v node >/dev/null 2>&1; then
  if [[ -s "${NVM_DIR:-$HOME/.nvm}/nvm.sh" ]]; then
    # shellcheck disable=SC1090
    . "${NVM_DIR:-$HOME/.nvm}/nvm.sh"
    nvm install --lts >/dev/null
    nvm use --lts >/dev/null
  else
    echo "SETUP_FAILED: node is unavailable and nvm is unavailable; provision Node >=18 in the sandbox" >&2
    exit 127
  fi
fi

command -v npm >/dev/null 2>&1 || { echo "SETUP_FAILED: npm is unavailable after Node setup" >&2; exit 127; }
node_major="$(node -p 'process.versions.node.split(".")[0]')"
(( node_major >= 18 )) || { echo "SETUP_FAILED: Node >=18 required (found $(node --version))" >&2; exit 1; }

# NVM activation is process-local. Persist the resolved binary directory so
# BASELINE/CANDIDATE fresh shells can source it before invoking node/npm.
node_bin_dir="$(cd "$(dirname "$(command -v node)")" && pwd)"
printf '# Generated by prepare_sandbox.sh; source this file in later phases.\nexport PATH="%s:$PATH"\n' "$node_bin_dir" > "$runtime_env"

install_if_needed() {
  local dir="$1"; shift
  local lock="$1"; shift
  local deps="$dir/node_modules"
  local stamp="$dir/.aegis-lock.sha256"
  local digest="$(shasum -a 256 "$lock" | awk '{print $1}')"
  if [[ -d "$deps" && -f "$stamp" && "$(<"$stamp")" == "$digest" ]]; then
    echo "SKIP: dependencies already prepared in $dir"
    return
  fi
  (cd "$dir" && "$@")
  printf '%s' "$digest" > "$stamp"
  echo "INSTALLED: $dir"
}

if [[ ! -d "$repo_dir" ]]; then
  echo "SETUP_FAILED: repository directory does not exist: $repo_dir" >&2
  exit 2
fi
if [[ ! -f "$repo_dir/package.json" ]]; then
  echo "SETUP_FAILED: package.json is missing from $repo_dir" >&2
  exit 2
fi
if [[ -z "$manager" ]]; then
  if [[ -f "$repo_dir/package-lock.json" ]]; then manager=npm
  elif [[ -f "$repo_dir/pnpm-lock.yaml" ]]; then manager=pnpm
  elif [[ -f "$repo_dir/yarn.lock" ]]; then manager=yarn
  elif [[ -f "$repo_dir/bun.lockb" || -f "$repo_dir/bun.lock" ]]; then
    echo "SETUP_FAILED: Bun lockfile detected; Bun is unsupported (use npm, pnpm, or Yarn)" >&2
    exit 2
  else echo "SETUP_FAILED: no supported package-manager lockfile found in $repo_dir; report package_manager=unknown and status=unresolved" >&2; exit 2
  fi
fi
case "$manager" in
  npm) lockfile="$repo_dir/package-lock.json" ;;
  pnpm) lockfile="$repo_dir/pnpm-lock.yaml" ;;
  yarn) lockfile="$repo_dir/yarn.lock" ;;
  bun) echo "SETUP_FAILED: Bun is unsupported (use npm, pnpm, or Yarn)" >&2; exit 2 ;;
  *) echo "SETUP_FAILED: unsupported package manager '$manager'" >&2; exit 2 ;;
esac
if [[ ! -f "$lockfile" ]]; then
  echo "SETUP_FAILED: $manager was selected but required lockfile is missing: $lockfile; report package_manager=unknown and status=unresolved" >&2
  exit 2
fi

# Use the repository's pinned packageManager declaration when available.
manager_spec="$(node -e 'const p=require(process.argv[1]); process.stdout.write(p.packageManager || "")' "$repo_dir/package.json")"
if [[ -n "$manager_spec" ]]; then
  declared_manager="${manager_spec%@*}"
  if [[ "$declared_manager" != "$manager" ]]; then
    echo "SETUP_FAILED: lockfile selects $manager but package.json pins $manager_spec" >&2
    exit 2
  fi
fi

if [[ "$manager" == pnpm || "$manager" == yarn ]]; then
  if [[ -z "$manager_spec" ]]; then
    echo "SETUP_FAILED: $manager requires a pinned packageManager field in $repo_dir/package.json" >&2
    exit 2
  fi
  if ! command -v corepack >/dev/null 2>&1; then
    echo "SETUP_FAILED: corepack is unavailable; cannot provision pinned $manager_spec" >&2
    exit 127
  fi
  if ! corepack enable >/dev/null 2>&1; then
    echo "SETUP_FAILED: corepack enable failed while provisioning $manager_spec" >&2
    exit 1
  fi
  if ! corepack prepare "$manager_spec" --activate >/dev/null 2>&1; then
    echo "SETUP_FAILED: corepack could not provision pinned $manager_spec" >&2
    exit 1
  fi
  if ! command -v "$manager" >/dev/null 2>&1; then
    echo "SETUP_FAILED: $manager is still unavailable after provisioning $manager_spec" >&2
    exit 127
  fi
fi
install_if_needed "$skill_dir/scripts" "$skill_dir/scripts/package-lock.json" npm ci
case "$manager" in
  npm)  install_if_needed "$repo_dir" "$lockfile" npm ci ;;
  pnpm) install_if_needed "$repo_dir" "$lockfile" pnpm install --frozen-lockfile ;;
  yarn) install_if_needed "$repo_dir" "$lockfile" yarn install --immutable ;;
esac

printf 'node=%s\nnpm=%s\nmanager=%s\nruntime_env=%s\n' "$(node --version)" "$(npm --version)" "$manager" "$runtime_env" > "$marker"
echo "PREPARED: $marker"
