#!/usr/bin/env bash
set -Eeuo pipefail

# One-time, idempotent AEGIS setup. Run this before BASELINE.
# Usage: prepare_sandbox.sh <repository> [npm|pnpm|yarn]

repo_dir="${1:?repository path required}"
manager="${2:-}"
skill_dir="$(cd "$(dirname "$0")/.." && pwd)"
marker="$skill_dir/.aegis-prepared"
runtime_env="$skill_dir/.aegis-node-env"

node_usable() {
  command -v node >/dev/null 2>&1 && command -v npm >/dev/null 2>&1 || return 1
  local major
  major="$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null || echo 0)"
  (( major >= 18 ))
}

provision_node() {
  # Prefer an existing version manager because it handles architecture.
  if [[ -s "${NVM_DIR:-$HOME/.nvm}/nvm.sh" ]]; then
    echo "SETUP_ATTEMPT: NVM"
    # shellcheck disable=SC1090
    . "${NVM_DIR:-$HOME/.nvm}/nvm.sh"
    if nvm install --lts >/dev/null && nvm use --lts >/dev/null && node_usable; then return 0; fi
    echo "SETUP_ATTEMPT_FAILED: NVM could not provide Node >=18/npm" >&2
  fi
  if command -v fnm >/dev/null 2>&1; then
    echo "SETUP_ATTEMPT: fnm"
    if fnm install --lts >/dev/null && fnm use --lts >/dev/null && node_usable; then return 0; fi
    echo "SETUP_ATTEMPT_FAILED: fnm could not provide Node >=18/npm" >&2
  fi

  # Self-contained fallback: download the official Node binary into the
  # sandbox skill directory; no global or host installation is required.
  local version="${AEGIS_NODE_VERSION:-22.22.1}" os arch archive_url runtime_dir tmp_archive
  os="$(uname -s | tr '[:upper:]' '[:lower:]')"
  case "$(uname -m)" in
    x86_64|amd64) arch=x64 ;;
    aarch64|arm64) arch=arm64 ;;
    *) echo "SETUP_ATTEMPT: unsupported architecture $(uname -m) for Node binary" >&2 ; arch="" ;;
  esac
  if [[ "$os" == linux && -n "$arch" ]] && { command -v curl >/dev/null 2>&1 || command -v wget >/dev/null 2>&1; }; then
    runtime_dir="$skill_dir/.runtime/node-v$version-linux-$arch"
    if [[ ! -x "$runtime_dir/bin/node" ]]; then
      tmp_archive="${TMPDIR:-/tmp}/aegis-node-$version-$arch.tar.xz"
      archive_url="https://nodejs.org/dist/v$version/node-v$version-linux-$arch.tar.xz"
      echo "SETUP_ATTEMPT: official Node binary $archive_url"
      if command -v curl >/dev/null 2>&1; then
        curl -fsSL "$archive_url" -o "$tmp_archive" || echo "SETUP_ATTEMPT_FAILED: download failed ($archive_url)" >&2
      else
        wget -q "$archive_url" -O "$tmp_archive" || echo "SETUP_ATTEMPT_FAILED: download failed ($archive_url)" >&2
      fi
      if [[ -s "$tmp_archive" ]]; then
        mkdir -p "$skill_dir/.runtime"
        tar -xJf "$tmp_archive" -C "$skill_dir/.runtime" || echo "SETUP_ATTEMPT_FAILED: could not extract $tmp_archive" >&2
      fi
    fi
    if [[ -x "$runtime_dir/bin/node" && -x "$runtime_dir/bin/npm" ]]; then
      export PATH="$runtime_dir/bin:$PATH"
      node_usable && return 0
    fi
  fi

  # Last resort for Debian-like sandboxes where apt is available and we are
  # root. Validate the resulting major version; distro packages may be old.
  if command -v apt-get >/dev/null 2>&1 && [[ "$(id -u)" == 0 ]]; then
    apt-get update -qq >/dev/null 2>&1 && apt-get install -y -qq nodejs npm >/dev/null 2>&1 || true
    node_usable && return 0
  fi
  return 1
}

if ! node_usable; then
  provision_node || {
    echo "SETUP_FAILED: Node >=18/npm unavailable after NVM, fnm, official binary, and apt fallbacks" >&2
    exit 127
  }
fi
node_usable || { echo "SETUP_FAILED: Node >=18 and npm are required (found ${node:-unavailable})" >&2; exit 1; }

# NVM activation is process-local. Persist the resolved binary directory so
# BASELINE/CANDIDATE fresh shells can source it before invoking node/npm.
node_bin_dir="$(cd "$(dirname "$(command -v node)")" && pwd)"
printf '# Generated by prepare_sandbox.sh; source this file in later phases.\nexport PATH="%s:$PATH"\n' "$node_bin_dir" > "$runtime_env"

install_if_needed() {
  local dir="$1"; shift
  local lock="$1"; shift
  local deps="$dir/node_modules"
  local stamp="$dir/.aegis-lock.sha256"
  local digest="$(shasum -a 256 "$lock" | awk '{print $1}')"
  if [[ -d "$deps" && -f "$stamp" && "$(<"$stamp")" == "$digest" ]]; then
    echo "SKIP: dependencies already prepared in $dir"
    return
  fi
  (cd "$dir" && "$@")
  printf '%s' "$digest" > "$stamp"
  echo "INSTALLED: $dir"
}

if [[ ! -d "$repo_dir" ]]; then
  echo "SETUP_FAILED: repository directory does not exist: $repo_dir" >&2
  exit 2
fi
if [[ ! -f "$repo_dir/package.json" ]]; then
  echo "SETUP_FAILED: package.json is missing from $repo_dir" >&2
  exit 2
fi
if [[ -z "$manager" ]]; then
  if [[ -f "$repo_dir/package-lock.json" ]]; then manager=npm
  elif [[ -f "$repo_dir/pnpm-lock.yaml" ]]; then manager=pnpm
  elif [[ -f "$repo_dir/yarn.lock" ]]; then manager=yarn
  elif [[ -f "$repo_dir/bun.lockb" || -f "$repo_dir/bun.lock" ]]; then
    echo "SETUP_FAILED: Bun lockfile detected; Bun is unsupported (use npm, pnpm, or Yarn)" >&2
    exit 2
  else echo "SETUP_FAILED: no supported package-manager lockfile found in $repo_dir; report package_manager=unknown and status=unresolved" >&2; exit 2
  fi
fi
case "$manager" in
  npm) lockfile="$repo_dir/package-lock.json" ;;
  pnpm) lockfile="$repo_dir/pnpm-lock.yaml" ;;
  yarn) lockfile="$repo_dir/yarn.lock" ;;
  bun) echo "SETUP_FAILED: Bun is unsupported (use npm, pnpm, or Yarn)" >&2; exit 2 ;;
  *) echo "SETUP_FAILED: unsupported package manager '$manager'" >&2; exit 2 ;;
esac
if [[ ! -f "$lockfile" ]]; then
  echo "SETUP_FAILED: $manager was selected but required lockfile is missing: $lockfile; report package_manager=unknown and status=unresolved" >&2
  exit 2
fi

# Use the repository's pinned packageManager declaration when available.
manager_spec="$(node -e 'const p=require(process.argv[1]); process.stdout.write(p.packageManager || "")' "$repo_dir/package.json")"
if [[ -n "$manager_spec" ]]; then
  declared_manager="${manager_spec%@*}"
  if [[ "$declared_manager" != "$manager" ]]; then
    echo "SETUP_FAILED: lockfile selects $manager but package.json pins $manager_spec" >&2
    exit 2
  fi
fi

if [[ "$manager" == pnpm || "$manager" == yarn ]]; then
  if [[ -z "$manager_spec" ]]; then
    echo "SETUP_FAILED: $manager requires a pinned packageManager field in $repo_dir/package.json" >&2
    exit 2
  fi
  if ! command -v corepack >/dev/null 2>&1; then
    echo "SETUP_FAILED: corepack is unavailable; cannot provision pinned $manager_spec" >&2
    exit 127
  fi
  if ! corepack enable >/dev/null 2>&1; then
    echo "SETUP_FAILED: corepack enable failed while provisioning $manager_spec" >&2
    exit 1
  fi
  if ! corepack prepare "$manager_spec" --activate >/dev/null 2>&1; then
    echo "SETUP_FAILED: corepack could not provision pinned $manager_spec" >&2
    exit 1
  fi
  if ! command -v "$manager" >/dev/null 2>&1; then
    echo "SETUP_FAILED: $manager is still unavailable after provisioning $manager_spec" >&2
    exit 127
  fi
fi
install_if_needed "$skill_dir/scripts" "$skill_dir/scripts/package-lock.json" npm ci
case "$manager" in
  npm)  install_if_needed "$repo_dir" "$lockfile" npm ci ;;
  pnpm) install_if_needed "$repo_dir" "$lockfile" pnpm install --frozen-lockfile ;;
  yarn) install_if_needed "$repo_dir" "$lockfile" yarn install --immutable ;;
esac

printf 'node=%s\nnpm=%s\nmanager=%s\nruntime_env=%s\n' "$(node --version)" "$(npm --version)" "$manager" "$runtime_env" > "$marker"
echo "PREPARED: $marker"
